worker_processes  1;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events { worker_connections 1024; }

stream {
    upstream dsn_node1_ws {
        server node1:8080;
    }

    server {
        listen 8443 ssl;
        proxy_pass dsn_node1_ws;
        ssl_certificate /etc/nginx/certs/wss.crt;
        ssl_certificate_key /etc/nginx/certs/wss.key;
        ssl_protocols TLSv1.2 TLSv1.3;
    }
}
